num_classes: 6 # 6 for mortality task, 2 for ICD-9 tasks
batch_size: 32
learning_rate: 0.1
num_epochs: 50
dropout_p: 0.1
gpus: [0]
data_path: "data/mimic/im.pk"
num_cpus: 6
task_num: -1 # -1 is mortality, all others are for ICD-9 task

# OGM-GE settings
grad_mod_type: "OGM_GE" # Options: (None | 'OGM_GE' | 'OGM' | 'noise') 
alpha: 0.8 # recommended setting 0.8 for Crema-D 

# main settings that need to be checked
use_wandb: True
model_type: "ensemble"
group_name: "mimic_m6_ensemble_baseline_trainweightedsampler_lr=0.1"
seed: 5
use_scheduler: False 
