num_classes: 6 # 6 for mortality task, 2 for ICD-9 tasks
batch_size: 32
learning_rate: 0.1
num_epochs: 50
dropout_p: 0.1
gpus: [0]
data_path: "data/mimic/im.pk"
num_cpus: 6
task_num: -1 # -1 is mortality, 1 for ICD-9-1, 7 for ICD-9-7

# OGM-GE settings
grad_mod_type: "OGM_GE" # Options: (None | 'OGM_GE' | 'OGM' | 'noise') 
alpha: 0.1

# main settings that need to be checked
use_wandb: False
model_type: "ensemble"
group_name: "test dataset class" # "mimic_m6_qmf_lr=0.1"
seed: 10
use_scheduler: False
