num_classes: 6
batch_size: 32
learning_rate: 1.0e-4
num_epochs: 2
dropout_p: 0.1
text_embedder: "all-mpnet-base-v2"
trained_model_version: "version_87"
trained_model_path: null
gpus: [0]
data_path: "data/im.pk"
num_cpus: 1