num_classes: 28
batch_size: 64
learning_rate: 1.0e-3 # paper starts here and decays to 1e-4
num_epochs: 100
dropout_p: 0.1
gpus: [0]
data_path: "../data/ave/"
num_cpus: 12

# main settings that need to be checked
use_wandb: True
model_type: "jprobas"
group_name: "ave_cls28_jprobas_seeds" # "ave_cls10_jlogits_seeds" 
seed: 5
use_scheduler: True 