num_classes: 101 # emotion classification
batch_size: 128
learning_rate: 0.01
num_epochs: 60
gpus: [0]
data_path: "data/food101/"
num_cpus: 12

# main settings that need to be checked
use_wandb: True
model_type: "jlogits"
group_name: "food101_cls101_jlogits_hpo_again" 
seed: 5
use_scheduler: True