num_classes: 101 # emotion classification
batch_size: 64
learning_rate: 1.0e-3 # paper starts here and decays to 1e-4
num_epochs: 100
dropout_p: 0.1
gpus: [0]
data_path: "../data/food101/"
num_cpus: 12

# main settings that need to be checked
use_wandb: True
model_type: "ensemble"
group_name: "food101_test" # cremad_cls28_ensemble_seeds
seed: 0
use_scheduler: True 