num_classes: 6 # emotion classification
batch_size: 64
learning_rate: 1.0e-3 # paper starts here and decays to 1e-4
num_epochs: 100
dropout_p: 0.1
gpus: [0]
data_path: "../data/cremad/"
num_cpus: 12

# main settings that need to be checked
use_wandb: True
model_type: "jlogits"
group_name: "cremad_cls6_jlogits_seeds" # cremad_cls28_ensemble_seeds
seed: 5
use_scheduler: True 