num_classes: 20
batch_size: 32
learning_rate: 1.0e-4
num_epochs: 30
dropout_p: 0.1
gpus: [0]
data_path: "../data/mustard/"
num_cpus: 2

# main settings that need to be checked
model_type: "ensemble"
group_name: "mustard_cls20_ensemble_seeds"
seed: 0