num_classes: 2
batch_size: 32
learning_rate: 5.0e-4
num_epochs: 100
max_seq_len: 40
dropout_p: 0.1
gpus: [0]
data_path: "../data/mustard/sarcasm.pkl"
num_cpus: 2

# main settings that need to be checked
use_wandb: True
model_type: "jlogits"
group_name: "mustard_test" # "mustard_cls2_jlogits_seeds"
seed: 0