# NOTE: might need to rewrite WeightedRandomSampler in get_data.py into DistributedSampler 

num_classes: 309 
batch_size: 224
learning_rate: 1.0e-2 # paper starts here and decays to 1e-4
num_epochs: 60
dropout_p: 0.1
gpus: [0] # list of GPUs for multi-gpu training
data_path: "../data/vggsound/"
num_cpus: 12
use_video_frames: 4 # number of video frames to stack for video input, more is better (kinda like data aug) but limited by VRAM, max 8

# main settings that need to be checked
use_wandb: True
model_type: "jprobas" # options: jlogits, jprobas, ensemble
group_name: "vggsound_cls309_jprobas_seeds" # vggsound_cls309_ensemble_seeds
seed: 0
use_scheduler: False